# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: make publish dir
        run: mkdir /home/runner/work/publish

      # Runs a set of commands using the runners shell
      - name: build gfwlist
        run: |
          sh gfwlist2dnsmasq.sh gen
          ls -lah /home/runner/work/publish/
          
      # Runs a set of commands using the runners shell
      - name: build ipcidr
        run: |
          sh ip4cidr2ipset.sh
          ls -lah /home/runner/work/publish/
          
      - name: git push
        run: |
          cd /home/runner/work/publish/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b hidden
          git add .
          git commit -m "release"
          git remote add publish "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f hidden hidden
